#line 1 "glsllexer.cpp"

#line 3 "glsllexer.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

    /* The c++ scanner is a mess. The FlexLexer.h header file relies on the
     * following macro. This is required in order to pass the c++-multiple-scanners
     * test in the regression suite. We get reports that it breaks inheritance.
     * We will address this in a future release of flex, or omit the C++ scanner
     * altogether.
     */
    #define yyFlexLexer yyFlexLexer

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */
#include <iostream>
#include <errno.h>
#include <cstdlib>
#include <cstdio>
#include <cstring>
/* end standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{

	std::streambuf* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

#define yytext_ptr yytext
#define YY_INTERACTIVE

#include <FlexLexer.h>

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 54
#define YY_END_OF_BUFFER 55
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[273] =
    {   0,
       37,   37,   55,   53,   36,   36,   37,   53,   49,   37,
       48,   37,   51,   37,   46,   46,   46,   37,   37,   49,
       50,   50,   50,   50,   37,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   37,   53,   35,   36,   37,   25,   38,
        0,   46,   41,   34,   47,   46,   46,   50,   46,   46,
       46,   50,   50,   43,   43,   42,   50,   50,   50,   40,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   12,
       25,   50,   50,   50,   18,   20,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,

       50,   50,   50,   39,   52,   35,   46,   46,   46,   46,
       34,   46,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   13,   50,
       33,   50,   50,   50,   50,   50,   21,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   52,
       50,   50,   50,   50,   44,   50,   50,   16,   50,   50,
       50,   50,   50,   19,    7,   50,   50,   50,   50,   50,
       32,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       31,   50,   50,   50,   50,   45,   50,   10,   50,    2,
       50,   50,   50,   22,   50,   50,   50,   50,   50,   50,

       50,   50,   50,   50,   50,   50,   50,   14,   50,   29,
       29,   50,   50,   50,   50,   50,   50,   50,    5,   32,
       50,   50,   23,   50,    8,   28,   15,   50,   50,   29,
       50,   50,   50,   50,   17,   26,   50,   50,   50,   50,
       50,    3,    4,   50,   50,    6,   11,   50,   50,   50,
       50,   50,   50,   50,    1,   24,   50,   50,   50,   27,
       50,   50,   50,   50,   50,   50,   50,   50,   30,   50,
        9,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    4,    7,    1,    8,
        9,    4,    4,   10,   11,   12,   13,   14,   15,   16,
       17,   18,   14,   14,   14,   14,   14,   19,   10,   20,
       21,   22,   23,   10,   24,   25,   26,   27,   28,   29,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   30,   31,   32,   28,   28,   28,   28,   28,   28,
        9,   10,    9,   33,   10,    1,   34,   35,   36,   37,

       38,   39,   40,   41,   42,   28,   43,   44,   45,   46,
       47,   48,   28,   49,   50,   51,   52,   53,   54,   55,
       56,   28,    9,   57,    9,   10,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   58,    1,
       59,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   60,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[61] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    3,    1,    1,
        1,    3,    1,    3,    3,    3,    3,    3,    1,    1,
        1,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[276] =
    {   0,
        0,  159,  162,  941,   59,   61,  133,   90,  941,   58,
      941,   55,  109,   54,   72,  117,  101,   57,   60,  104,
       83,   84,   85,   90,   73,   91,   96,  129,  110,  102,
      139,  105,  152,  147,  158,   93,  160,  166,  163,  176,
      191,  182,  177,   64,   61,    0,  124,  941,  941,  941,
      231,  238,  941,    0,  941,  244,   85,  185,  199,  205,
      211,  214,  255,   88,  941,  941,  256,  228,  223,  941,
      220,  257,  262,  268,  279,  281,  286,  289,  291,  297,
      299,  300,  302,  305,  307,  308,  310,  313,  322,  323,
      325,  330,  331,  339,  340,  345,  348,  350,  355,  358,

      366,  367,  369,  941,   42,    0,    0,   63,   31,  941,
        0,  398,  377,  380,  383,  391,  392,  398,  409,  393,
      411,  412,  417,  420,  423,  426,  428,  431,  436,  443,
      444,  449,  454,  461,  464,  462,  463,  476,  477,  478,
      484,  485,  479,  490,  493,  495,  498,  501,  509,   16,
      510,  511,  512,  527,  528,  534,  536,  537,  544,  546,
      549,  552,  554,  555,  560,  561,  562,  569,  563,  570,
      572,  575,  577,  582,  584,  587,  590,  593,  595,  598,
      608,  609,  622,  624,  625,  627,  633,  636,  638,  641,
      643,  646,  649,  651,  652,  657,  654,  664,  659,  665,

      671,  676,  679,  684,  685,  687,  692,  694,  695,  700,
      710,  711,  713,  716,  721,  722,  731,  729,  732,  734,
      737,  740,  742,  745,  748,  750,  758,  761,  763,  766,
      768,  769,  771,  776,  778,  779,  781,  784,  787,  789,
      814,  790,  792,  803,  804,  805,  811,  816,  831,  826,
      833,  841,  842,  843,  844,  851,  857,  852,  858,  863,
      864,  865,  866,  873,  875,  874,  880,  881,  883,  888,
      890,  941,   65,  934,  937
    } ;

static const flex_int16_t yy_def[276] =
    {   0,
      272,    1,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  273,  273,   16,  272,  272,  272,
      273,  273,  273,  273,  272,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  272,  272,  274,  272,  272,  272,  272,
      272,  272,  272,  275,  272,  272,   16,  273,  273,  273,
      273,  273,  273,  272,  272,  272,  273,  273,  273,  272,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,

      273,  273,  273,  272,  272,  274,   52,  272,  272,  272,
      275,  272,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  272,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,

      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,    0,  272,  272,  272
    } ;

static const flex_int16_t yy_nxt[1002] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   11,    9,
       12,   13,   14,   15,   16,   17,   15,   15,    9,   18,
        7,   19,   20,   21,   22,   21,   21,   21,   23,   21,
       21,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       32,   33,   21,   34,   35,   36,   37,   38,   39,   40,
       24,   41,   42,   43,   21,   21,   44,    4,    4,   45,
       47,   47,   47,   47,   50,   51,   54,   58,   52,   52,
       52,   52,   52,  150,   48,   48,   64,   48,   48,   55,
       48,   65,  110,   56,   48,   57,   57,   57,   57,   57,
       55,   55,   55,   48,  272,  272,  272,   55,   55,  150,

       55,  272,  272,   55,  272,   70,  109,  272,   65,   55,
       59,   58,   55,  272,  110,   60,  272,   55,   68,  105,
      104,  272,   66,   61,   55,   47,   47,   63,   56,   53,
       57,   57,   57,   57,   57,   67,   55,   49,   69,   90,
      272,   71,   72,   62,   73,   82,   55,   78,   74,   81,
      272,   79,   81,   48,   55,   59,   80,   81,  272,   55,
       60,  272,   75,  272,   46,   55,   76,   55,   61,  272,
       55,  272,   68,   55,  272,   77,  272,  272,  272,  272,
       88,  272,   83,   55,   55,   84,  272,  272,  272,   55,
       85,   89,   55,  272,   81,  272,  272,   86,   55,   81,

       93,   87,  272,  272,   74,   81,   55,   81,  272,   94,
      272,   91,   55,  272,   92,  100,  272,  103,   55,  101,
       95,   55,  272,  272,   81,  272,   96,   55,  102,   97,
       55,  272,   98,  272,  272,   55,   99,  113,   81,  272,
       87,   51,   60,   74,   52,   52,   52,   52,   52,   56,
       61,  107,  107,  107,  107,  107,   61,  112,  112,  112,
      112,  112,   55,   55,   55,  272,  272,  272,  272,   55,
      118,  116,  272,  272,  117,   55,  108,  272,  113,  272,
      272,  109,  108,  272,  114,  272,   55,  109,   55,  110,
      272,  272,  272,   55,  115,  110,   55,  272,   55,  120,

      272,  272,  272,  119,   55,  101,   55,   55,  272,   55,
      272,  272,   55,  272,   55,   55,  272,   55,  272,  272,
       55,  272,  272,  272,  272,  272,  122,  124,  121,   55,
       55,  123,   55,  272,  272,  127,  272,   55,   55,  272,
      125,  272,  272,  133,  272,  272,   55,   55,  128,  126,
      272,  272,   55,  129,  130,   55,  272,   55,  131,  272,
      132,  272,   55,  272,  272,   55,  272,  138,  134,  272,
      136,  272,  135,   55,   55,  137,   55,  272,  272,  272,
      272,  139,  272,  140,   55,  272,  141,   55,  272,  143,
       55,  272,  272,  142,  272,  144,  145,  272,   55,   55,

       55,  147,  272,  272,  272,   55,  146,  272,  148,  272,
      149,  112,  112,  112,  112,  112,   55,  152,   55,   55,
      272,  153,  272,  272,   55,  151,  157,   55,  272,  155,
       55,  272,  272,   55,  272,   55,  108,  272,   55,  272,
      154,  109,  272,   55,  272,  272,  156,  272,  158,  110,
       55,   55,  131,  162,  272,  272,   55,  272,  163,  272,
      272,   55,  159,  164,  166,  272,  160,  161,   55,   55,
       55,   55,  272,  272,  272,  272,  272,  272,  165,  171,
      171,  171,  168,   55,   55,   55,   55,  272,  272,  272,
      272,   55,   55,  272,  167,  272,  272,   55,  169,  172,

       55,  272,   55,  272,  272,   55,  272,  170,   55,  272,
      272,  173,  272,  181,  181,  181,   55,   55,   55,   55,
      272,  272,  272,  272,  272,  175,  272,  272,  174,  178,
      176,  179,  272,  272,   55,   55,  177,  131,  272,  272,
      131,   55,  272,   55,   55,  272,  184,  272,  272,  185,
      180,   55,  182,   55,  272,  272,   55,  272,  183,   55,
      272,   55,   55,  272,  186,  272,  272,   55,   55,   55,
       55,  272,  272,  272,  272,  187,   55,   55,  188,   55,
      272,  272,   55,  272,   55,  272,  272,  193,  272,   55,
      191,   55,  189,  272,   55,  272,  190,   55,  272,  272,

       55,  272,   55,  192,  272,   55,  272,  272,  272,  272,
      196,  131,  194,  272,  272,   55,   55,  195,  200,  272,
      272,  197,  272,  199,  272,  204,  198,  202,  205,   55,
      201,   55,   55,  272,   55,  272,  272,  203,  272,  207,
       55,  206,  272,   55,  272,   55,  208,  272,   55,  272,
       55,  272,  272,   55,  272,  209,   55,  272,   55,   55,
      272,   55,  272,  272,   55,  272,   55,  212,  272,  272,
      272,   55,   55,  211,  210,  272,  272,  272,   55,  220,
      220,  220,  272,   55,  213,  272,   55,  272,  214,  215,
      272,   55,   55,  217,   55,  272,  272,  216,  272,   55,

      218,   55,   55,  272,  219,  272,  272,   55,  221,  272,
      272,  272,  272,  224,  222,  272,  223,   55,   55,  225,
       55,  272,  272,   55,  272,  227,  272,  272,   55,   55,
      231,  272,  272,  272,  226,  228,   55,  229,   55,   55,
      272,   55,  272,  272,   55,  272,  272,   55,  272,   55,
      230,  272,   55,  272,  233,   55,  272,   55,  236,  272,
      272,  272,  232,  272,  237,   55,  238,  234,   55,  272,
       55,  235,  272,   55,  272,   55,   55,  272,   55,  272,
      272,  240,  272,   55,  239,   55,   55,  272,   55,  272,
      272,   55,  272,  241,   55,  272,   55,   55,  272,   55,

      272,  272,  243,  272,  272,  242,  272,  246,  244,  272,
       55,   55,   55,  247,  272,  272,  272,  272,   55,  245,
      272,   55,  272,   55,  250,  272,  248,  272,  252,  252,
      252,  272,  249,   55,  272,  251,  254,  272,   55,  253,
       55,  255,  272,  272,  272,  257,  257,  257,   55,   55,
       55,   55,  272,  272,  272,  272,  258,  272,   55,   55,
      272,  259,  272,  272,   55,   55,  256,  230,  272,  272,
       55,   55,   55,   55,  272,  272,  272,  272,  260,  262,
       55,   55,   55,  211,  272,  272,  272,   55,   55,  272,
       55,  272,  272,  261,  272,   55,  272,   55,  265,  272,

      267,  272,  272,  263,  272,  272,  272,  272,  264,  272,
      272,  266,  230,  272,  268,  272,  272,  211,  272,  272,
      272,  272,  272,  272,  272,  271,  272,  269,  272,  272,
      272,  272,  272,  270,  106,  272,  106,  111,  272,  111,
        3,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,

      272
    } ;

static const flex_int16_t yy_chk[1002] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        5,    5,    6,    6,   10,   12,   14,  273,   12,   12,
       12,   12,   12,  150,   14,   12,   18,   18,   10,   15,
       19,   19,  109,   15,   44,   15,   15,   15,   15,   15,
       21,   22,   23,   25,   21,   22,   23,   24,   26,  105,

       36,   24,   26,   27,   36,   25,  108,   27,   64,   30,
       15,   57,   32,   30,  108,   15,   32,   29,   23,   45,
       44,   29,   20,   15,   16,   47,   47,   17,   16,   13,
       16,   16,   16,   16,   16,   22,   28,    8,   24,   36,
       28,   26,   27,   16,   27,   30,   31,   29,   27,   30,
       31,   29,   32,    7,   34,   16,   29,   29,   34,   33,
       16,    3,   28,   33,    2,   35,   28,   37,   16,   35,
       39,   37,   31,   38,   39,   28,    0,   38,    0,    0,
       34,    0,   31,   40,   43,   31,    0,   40,   43,   42,
       33,   35,   58,   42,   34,    0,   58,   33,   41,   33,

       39,   33,   41,    0,   33,   35,   59,   37,    0,   40,
       59,   37,   60,    0,   38,   42,   60,   43,   61,   42,
       40,   62,   61,    0,   43,   62,   40,   71,   42,   40,
       69,   71,   41,    0,   69,   68,   41,   62,   41,   68,
       41,   51,   59,   41,   51,   51,   51,   51,   51,   52,
       59,   52,   52,   52,   52,   52,   60,   56,   56,   56,
       56,   56,   63,   67,   72,    0,   63,   67,   72,   73,
       71,   68,    0,   73,   69,   74,   52,    0,   63,   74,
        0,   52,   56,    0,   63,    0,   75,   56,   76,   52,
       75,    0,   76,   77,   67,   56,   78,   77,   79,   73,

       78,    0,   79,   72,   80,   74,   81,   82,   80,   83,
       81,   82,   84,   83,   85,   86,   84,   87,   85,   86,
       88,   87,    0,    0,   88,    0,   76,   78,   75,   89,
       90,   77,   91,   89,   90,   83,   91,   92,   93,    0,
       79,   92,   93,   87,    0,    0,   94,   95,   83,   82,
       94,   95,   96,   84,   86,   97,   96,   98,   86,   97,
       86,   98,   99,    0,    0,  100,   99,   92,   88,  100,
       90,    0,   89,  101,  102,   91,  103,  101,  102,    0,
      103,   93,    0,   94,  113,    0,   95,  114,  113,   97,
      115,  114,    0,   96,  115,   98,   99,    0,  116,  117,

      120,  101,  116,  117,  120,  118,  100,    0,  102,  118,
      103,  112,  112,  112,  112,  112,  119,  114,  121,  122,
      119,  115,  121,  122,  123,  113,  120,  124,  123,  117,
      125,  124,    0,  126,  125,  127,  112,  126,  128,  127,
      116,  112,  128,  129,    0,    0,  118,  129,  121,  112,
      130,  131,  119,  124,  130,  131,  132,    0,  125,    0,
      132,  133,  122,  126,  128,  133,  123,  123,  134,  136,
      137,  135,  134,  136,  137,  135,    0,    0,  127,  135,
      135,  135,  132,  138,  139,  140,  143,  138,  139,  140,
      143,  141,  142,    0,  130,  141,  142,  144,  133,  136,

      145,  144,  146,    0,  145,  147,  146,  134,  148,  147,
        0,  138,  148,  147,  147,  147,  149,  151,  152,  153,
      149,  151,  152,  153,    0,  140,    0,    0,  139,  143,
      141,  145,    0,    0,  154,  155,  142,  148,  154,  155,
      144,  156,    0,  157,  158,  156,  152,  157,  158,  153,
      146,  159,  149,  160,    0,  159,  161,  160,  151,  162,
      161,  163,  164,  162,  154,  163,  164,  165,  166,  167,
      169,  165,  166,  167,  169,  156,  168,  170,  157,  171,
      168,  170,  172,  171,  173,    0,  172,  163,  173,  174,
      161,  175,  159,  174,  176,  175,  160,  177,  176,    0,

      178,  177,  179,  162,  178,  180,  179,    0,    0,  180,
      169,  166,  167,    0,    0,  181,  182,  168,  173,  181,
      182,  170,    0,  172,    0,  177,  171,  175,  178,  183,
      174,  184,  185,  183,  186,  184,  185,  176,  186,  180,
      187,  179,    0,  188,  187,  189,  182,  188,  190,  189,
      191,    0,  190,  192,  191,  183,  193,  192,  194,  195,
      193,  197,  194,  195,  196,  197,  199,  187,  196,    0,
      199,  198,  200,  185,  184,  198,  200,    0,  201,  198,
      198,  198,  201,  202,  189,    0,  203,  202,  191,  192,
      203,  204,  205,  195,  206,  204,  205,  193,  206,  207,

      196,  208,  209,  207,  197,  208,  209,  210,  199,    0,
        0,  210,    0,  202,  200,    0,  201,  211,  212,  203,
      213,  211,  212,  214,  213,  205,    0,  214,  215,  216,
      210,    0,  215,  216,  204,  206,  218,  207,  217,  219,
      218,  220,  217,  219,  221,  220,    0,  222,  221,  223,
      209,  222,  224,  223,  213,  225,  224,  226,  216,  225,
        0,  226,  212,    0,  217,  227,  218,  214,  228,  227,
      229,  215,  228,  230,  229,  231,  232,  230,  233,  231,
      232,  222,  233,  234,  221,  235,  236,  234,  237,  235,
      236,  238,  237,  224,  239,  238,  240,  242,  239,  243,

      240,  242,  229,  243,    0,  228,    0,  233,  231,    0,
      244,  245,  246,  234,  244,  245,  246,    0,  247,  232,
        0,  241,  247,  248,  239,  241,  237,  248,  241,  241,
      241,    0,  238,  250,    0,  240,  244,  250,  249,  241,
      251,  245,  249,    0,  251,  249,  249,  249,  252,  253,
      254,  255,  252,  253,  254,  255,  249,    0,  256,  258,
        0,  250,  256,  258,  257,  259,  248,  252,  257,  259,
      260,  261,  262,  263,  260,  261,  262,  263,  251,  254,
      264,  266,  265,  257,  264,  266,  265,  267,  268,    0,
      269,  267,  268,  253,  269,  270,    0,  271,  261,  270,

      263,  271,    0,  258,    0,    0,    0,    0,  259,    0,
        0,  262,  265,    0,  264,    0,    0,  267,    0,    0,
        0,    0,    0,    0,    0,  270,    0,  266,    0,    0,
        0,    0,    0,  268,  274,    0,  274,  275,    0,  275,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,

      272
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "GlslLexer.lex"
/*! @file GlslLexer.lex
 * @brief Flex definitions for generating the GLSL lexer
 * @author Phil Rouse
 * @version 1.0
 * @date 07/05/2016
 */
#line 15 "GlslLexer.lex"
  #include "QsciLexerGlsl.h"
#line 713 "glsllexer.cpp"
#line 714 "glsllexer.cpp"

#define INITIAL 0

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
\
	if ( (int)(result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
#define YY_DECL int yyFlexLexer::yylex()
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin.rdbuf(std::cin.rdbuf());

		if ( ! yyout )
			yyout.rdbuf(std::cout.rdbuf());

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 18 "GlslLexer.lex"


#line 844 "glsllexer.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 273 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 941 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
#line 21 "GlslLexer.lex"
case 2:
#line 22 "GlslLexer.lex"
case 3:
#line 23 "GlslLexer.lex"
case 4:
#line 24 "GlslLexer.lex"
case 5:
#line 25 "GlslLexer.lex"
case 6:
#line 26 "GlslLexer.lex"
case 7:
#line 27 "GlslLexer.lex"
case 8:
#line 28 "GlslLexer.lex"
case 9:
#line 29 "GlslLexer.lex"
case 10:
#line 30 "GlslLexer.lex"
case 11:
#line 31 "GlslLexer.lex"
case 12:
#line 32 "GlslLexer.lex"
case 13:
#line 33 "GlslLexer.lex"
case 14:
#line 34 "GlslLexer.lex"
case 15:
#line 35 "GlslLexer.lex"
case 16:
#line 36 "GlslLexer.lex"
case 17:
#line 37 "GlslLexer.lex"
case 18:
#line 38 "GlslLexer.lex"
case 19:
#line 39 "GlslLexer.lex"
case 20:
#line 40 "GlslLexer.lex"
case 21:
#line 41 "GlslLexer.lex"
case 22:
#line 42 "GlslLexer.lex"
case 23:
#line 43 "GlslLexer.lex"
case 24:
#line 44 "GlslLexer.lex"
case 25:
#line 45 "GlslLexer.lex"
case 26:
#line 46 "GlslLexer.lex"
case 27:
#line 47 "GlslLexer.lex"
case 28:
YY_RULE_SETUP
#line 47 "GlslLexer.lex"
{ return QsciLexerGLSL::StyleType::KEYWORD; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 49 "GlslLexer.lex"
{ return QsciLexerGLSL::StyleType::DATATYPE; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 50 "GlslLexer.lex"
{ return QsciLexerGLSL::StyleType::DATATYPE; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 51 "GlslLexer.lex"
{ return QsciLexerGLSL::StyleType::DATATYPE; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 52 "GlslLexer.lex"
{ return QsciLexerGLSL::StyleType::DATATYPE; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 53 "GlslLexer.lex"
{ return QsciLexerGLSL::StyleType::DATATYPE; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 55 "GlslLexer.lex"
{ return QsciLexerGLSL::StyleType::COMMENT; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 56 "GlslLexer.lex"
{ return QsciLexerGLSL::StyleType::HASHCOMMENT; }
	YY_BREAK
case 36:
/* rule 36 can match eol */
YY_RULE_SETUP
#line 57 "GlslLexer.lex"
{ return QsciLexerGLSL::StyleType::WHITESPACE; }
	YY_BREAK
case 37:
#line 60 "GlslLexer.lex"
case 38:
#line 61 "GlslLexer.lex"
case 39:
#line 62 "GlslLexer.lex"
case 40:
#line 63 "GlslLexer.lex"
case 41:
#line 64 "GlslLexer.lex"
case 42:
#line 65 "GlslLexer.lex"
case 43:
YY_RULE_SETUP
#line 65 "GlslLexer.lex"
{ return QsciLexerGLSL::StyleType::OPERATOR; }
	YY_BREAK
case 44:
#line 68 "GlslLexer.lex"
case 45:
#line 69 "GlslLexer.lex"
case 46:
YY_RULE_SETUP
#line 69 "GlslLexer.lex"
{ return QsciLexerGLSL::StyleType::NUMBER; }
	YY_BREAK
case 47:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 71 "GlslLexer.lex"
{ return QsciLexerGLSL::StyleType::FUNCTION; }
	YY_BREAK
case 48:
#line 73 "GlslLexer.lex"
case 49:
#line 74 "GlslLexer.lex"
case 50:
#line 75 "GlslLexer.lex"
case 51:
YY_RULE_SETUP
#line 75 "GlslLexer.lex"
{ return QsciLexerGLSL::StyleType::DEFAULT; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 77 "GlslLexer.lex"
{
                                yyleng = 1;
                                return QsciLexerGLSL::StyleType::ILLEGAL;
                              }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 81 "GlslLexer.lex"
{ return QsciLexerGLSL::StyleType::ILLEGAL; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 84 "GlslLexer.lex"
ECHO;
	YY_BREAK
#line 1065 "glsllexer.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin.rdbuf();
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* The contents of this function are C++ specific, so the () macro is not used.
 * This constructor simply maintains backward compatibility.
 * DEPRECATED
 */
yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout ):
	yyin(arg_yyin ? arg_yyin->rdbuf() : std::cin.rdbuf()),
	yyout(arg_yyout ? arg_yyout->rdbuf() : std::cout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::yyFlexLexer( std::istream& arg_yyin, std::ostream& arg_yyout ):
	yyin(arg_yyin.rdbuf()),
	yyout(arg_yyout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::ctor_common()
{
	yy_c_buf_p = 0;
	yy_init = 0;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = NULL;

	yy_buffer_stack = NULL;
	yy_buffer_stack_top = 0;
	yy_buffer_stack_max = 0;

	yy_state_buf = 0;

}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::~yyFlexLexer()
{
	delete [] yy_state_buf;
	yyfree( yy_start_stack  );
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yyfree( yy_buffer_stack  );
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream& new_in, std::ostream& new_out )
{
	// was if( new_in )
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE  ) );

	// was if( new_out )
	yyout.rdbuf(new_out.rdbuf());
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
{
	if( ! new_in ) {
		new_in = &yyin;
	}

	if ( ! new_out ) {
		new_out = &yyout;
	}

	switch_streams(*new_in, *new_out);
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
{
	if ( yyin.eof() || yyin.fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin.get( buf[0] );

	if ( yyin.eof() )
		return 0;

	if ( yyin.bad() )
		return -1;

	return 1;

#else
	(void) yyin.read( buf, max_size );

	if ( yyin.bad() )
		return -1;
	else
		return yyin.gcount();
#endif
}

void yyFlexLexer::LexerOutput( const char* buf, int size )
{
	(void) yyout.write( buf, size );
}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
int yyFlexLexer::yy_get_next_buffer()
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    yy_state_type yyFlexLexer::yy_get_previous_state()
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 273 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 273 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 272);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
    void yyFlexLexer::yyunput( int c, char* yy_bp)
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
#endif

    int yyFlexLexer::yyinput()
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyFlexLexer::yyrestart( std::istream& input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Delegate to the new version that takes an istream reference.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
void yyFlexLexer::yyrestart( std::istream* input_file )
{
	if( ! input_file ) {
		input_file = &yyin;
	}
	yyrestart( *input_file );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

    void yyFlexLexer::yy_load_buffer_state()
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin.rdbuf(YY_CURRENT_BUFFER_LVALUE->yy_input_file);
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream& file, int size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Delegate creation of buffers to the new version that takes an istream reference.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
	YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
{
	return yy_create_buffer( *file, size );
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream& file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file.rdbuf();
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

	b->yy_is_interactive = 0;
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yyFlexLexer::yypush_buffer_state (YY_BUFFER_STATE new_buffer)
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yyFlexLexer::yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
void yyFlexLexer::yyensure_buffer_stack(void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

    void yyFlexLexer::yy_push_state( int _new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc( new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc(
					(void *) (yy_start_stack), new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

    void yyFlexLexer::yy_pop_state()
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    int yyFlexLexer::yy_top_state()
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

void yyFlexLexer::LexerError( const char* msg )
{
    	std::cerr << msg << std::endl;
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 84 "GlslLexer.lex"


int yyFlexLexer::yywrap()   { return 1;}

